### ISSUE TITLE
Code 200 with Response Body ¨404 Not Found¨

### ISSUE THREAD

**Issue by aitorcelaya** [FraunhoferISST/DataspaceConnector#281]
I performed the /api/ids/connector/update call to register my connector at the IDS Broker. I installed the Broker locally in localhost. I tried registering the connector to my own Broker and I got a code 200 with a ¨404 Not Found¨ response body.

The expected behavior was the connector to register at the local Broker and then update resources. 

Instead of getting a Code 404, obtained a Code 200 mentioning ¨404 Not Found¨

![image](https://user-images.githubusercontent.com/82808687/119366237-0be93c00-bcb1-11eb-86dd-341d338f4bad.png)

OS: Ubuntu
Browser: Firefox
Version: 88.0

**Comment by ghost** [comment]
From a purely formal technical point of view, the return 200 is fine here, though admittedly confusing in conjunction with a Broker-HTML Error-Page 404 as the Brokers response.

- 200 indicates that the broker itself responds and was reachable (HTTP specification), regardless of the content of the received response.
- However, 404 as the response from the broker as HTML-page indicates that an incorrect endpoint was addressed and the used one could not be found for the concrete use-case.

Likely solution:
`/browse` is the frontend endpoint of the broker (_requests frontend_). 

The endpoint required for IDS-Messages is `/infrastructure`.

Please try to send the IDS-Message on `/infrastructure` instead of `/browse`.

Description for `/infrastructure`: _This endpoint serves as the main interaction point for onboarding and updating of metadata at the broker. Most probably the relevant messages are ConnectorAvailableMessage, ConnectorUnavailableMessage, ConnectorInactiveMessage, ConnectorUpdateMessage, ResourceAvailableMessage, ResourceUnavailableMessage, ResourceUpdateMessage._

In general, there is a good documentation of the endpoints of the open-core broker here:
https://app.swaggerhub.com/apis/idsa/IDS-Broker/1.3.1

**Comment by aitorcelaya** [comment]
Thank you for the response however the issue still remains. Same Code 200 with a html 404 Not Found response

![image](https://user-images.githubusercontent.com/82808687/120176969-2cad1680-c208-11eb-8457-68223cac1577.png)

**Comment by aitorcelaya** [comment]
The issue is now fixed. Thank you for the assistance!
